### ISSUE TITLE
why don't using plupload as a git submodule ?

### ISSUE THREAD

**Issue by shouze** [JoshuaEstes/sfPluploadPlugin#6]
plupload projet is on github too... so making it as submodule of this project could be a good thing to keep in sync with new version ;)

https://github.com/moxiecode/plupload

I've made a fork of the sfPluploadPlugin I can try to deal with this.

**Comment by JoshuaEstes** [comment]
It's mainly because most of the files aren't needed so I don't see a big reason to do it

**Comment by shouze** [comment]
Yep, sorry I discovered that project has no already ready for production repository ;)
